import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { prisma } from '../../db/prisma.js';
import { PLATFORMS } from '../../config/platforms.js';
import { notFound } from '../../lib/errors.js';
import type { StudentFilters } from '../students/students.service.js';
import {
  getStudentContests,
  getStudentDetail,
  getStudentHistory,
  getStudentRatings,
  getStudentTopics,
} from '../students/students.service.js';
import { getBatchAnalytics, getLeaderboard, getTopicAnalytics } from '../analytics/aggregate.service.js';

export type ReportFormat = 'xlsx' | 'csv' | 'pdf';

export interface GeneratedReport {
  buffer: Buffer;
  filename: string;
  contentType: string;
}

const CONTENT_TYPES: Record<ReportFormat, string> = {
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  csv: 'text/csv; charset=utf-8',
  pdf: 'application/pdf',
};

const HEADER_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E293B' } };

/** "Not published by the platform" must read differently from a real zero. */
const show = (value: number | null | undefined): string | number => (value === null || value === undefined ? 'N/A' : value);

function styleHeader(sheet: ExcelJS.Worksheet) {
  const row = sheet.getRow(1);
  row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  row.fill = HEADER_FILL;
  row.alignment = { vertical: 'middle' };
  row.height = 20;
  sheet.views = [{ state: 'frozen', ySplit: 1 }];
}

function autoWidth(sheet: ExcelJS.Worksheet, min = 10, max = 44) {
  sheet.columns.forEach((column) => {
    let width = min;
    column.eachCell?.({ includeEmpty: false }, (cell) => {
      width = Math.max(width, String(cell.value ?? '').length + 2);
    });
    column.width = Math.min(max, width);
  });
}

async function workbookToBuffer(workbook: ExcelJS.Workbook, format: 'xlsx' | 'csv'): Promise<Buffer> {
  if (format === 'csv') {
    // CSV holds a single sheet; the first one carries the primary table.
    return Buffer.from(await workbook.csv.writeBuffer({ sheetName: workbook.worksheets[0]?.name }) as ArrayBuffer);
  }
  return Buffer.from(await workbook.xlsx.writeBuffer() as ArrayBuffer);
}

const safeName = (value: string) => value.replace(/[^A-Za-z0-9._-]+/g, '_').slice(0, 60);

// ---------------------------------------------------------------------------
// Student report
// ---------------------------------------------------------------------------

export async function generateStudentReport(studentId: string, format: ReportFormat): Promise<GeneratedReport> {
  const student = await getStudentDetail(studentId);
  const [topics, contests, ratings, history] = await Promise.all([
    getStudentTopics(student.id),
    getStudentContests(student.id),
    getStudentRatings(student.id),
    getStudentHistory(student.id, undefined, 365),
  ]);

  const filename = `student-report-${safeName(student.studentId)}.${format}`;

  if (format === 'pdf') {
    return {
      buffer: await renderStudentPdf(student, topics, contests, history),
      filename,
      contentType: CONTENT_TYPES.pdf,
    };
  }

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Competitive Programming Student Performance Tracker';
  workbook.created = new Date();

  // -- Summary --------------------------------------------------------------
  const summary = workbook.addWorksheet('Summary');
  summary.columns = [
    { header: 'Field', key: 'field' },
    { header: 'Value', key: 'value' },
  ];
  const a = student.analytics;
  summary.addRows([
    { field: 'Student ID', value: student.studentId },
    { field: 'Name', value: student.name },
    { field: 'Email', value: student.email ?? 'N/A' },
    { field: 'College', value: student.college ?? 'N/A' },
    { field: 'Batch', value: student.batch ?? 'N/A' },
    { field: 'Branch', value: student.branch ?? 'N/A' },
    { field: 'Section', value: student.section ?? 'N/A' },
    { field: 'Competitive Programming Score (out of 100)', value: a?.hasData ? a.cpScore : 'N/A' },
    { field: 'Total Problems Solved', value: a?.hasData ? a.totalSolved : 'N/A' },
    // Easy/Medium/Hard are only real numbers when a platform published a split.
    { field: 'Easy Solved', value: a?.difficultyKnown ? a.easySolved : 'N/A' },
    { field: 'Medium Solved', value: a?.difficultyKnown ? a.mediumSolved : 'N/A' },
    { field: 'Hard Solved', value: a?.difficultyKnown ? a.hardSolved : 'N/A' },
    { field: 'Contests Participated', value: a?.contestsKnown ? a.totalContests : 'N/A' },
    { field: 'Best Contest Rank', value: show(a?.bestRank) },
    { field: 'Current Rating (best across platforms)', value: show(a?.currentRating) },
    { field: 'Peak Rating', value: show(a?.bestRating) },
    { field: 'Distinct Topics', value: a?.topicsKnown ? a.topicCount : 'N/A' },
    { field: 'Report Generated', value: new Date().toISOString() },
    { field: 'Note', value: 'The CP Score is generated by this application and is not an official platform metric.' },
  ]);
  styleHeader(summary);
  autoWidth(summary);

  // -- Platform profiles ----------------------------------------------------
  const platforms = workbook.addWorksheet('Platforms');
  platforms.columns = [
    { header: 'Platform', key: 'platform' },
    { header: 'Username', key: 'username' },
    { header: 'Profile URL', key: 'url' },
    { header: 'Status', key: 'status' },
    { header: 'Status Detail', key: 'detail' },
    { header: 'Solved', key: 'solved' },
    { header: 'Easy', key: 'easy' },
    { header: 'Medium', key: 'medium' },
    { header: 'Hard', key: 'hard' },
    { header: 'Rating', key: 'rating' },
    { header: 'Max Rating', key: 'maxRating' },
    { header: 'Global Rank', key: 'globalRank' },
    { header: 'Contests', key: 'contests' },
    { header: 'Last Updated', key: 'updated' },
  ];
  for (const p of student.platforms) {
    platforms.addRow({
      platform: PLATFORMS[p.platform].label,
      username: p.username,
      url: p.profileUrl,
      status: p.status,
      detail: p.statusMessage ?? '',
      solved: show(p.totalSolved),
      easy: show(p.easySolved),
      medium: show(p.mediumSolved),
      hard: show(p.hardSolved),
      rating: show(p.rating),
      maxRating: show(p.maxRating),
      globalRank: show(p.globalRank),
      contests: show(p.contestsAttended),
      updated: p.lastSuccessAt?.toISOString() ?? 'Never',
    });
  }
  styleHeader(platforms);
  autoWidth(platforms);

  // -- Topics ---------------------------------------------------------------
  const topicSheet = workbook.addWorksheet('Topics');
  topicSheet.columns = [
    { header: 'Topic', key: 'topic' },
    { header: 'Problems Solved', key: 'solved' },
  ];
  topicSheet.addRows(topics.unified.map((t) => ({ topic: t.topic, solved: t.problemsSolved })));
  styleHeader(topicSheet);
  autoWidth(topicSheet);

  // -- Skill matrix ---------------------------------------------------------
  const skillSheet = workbook.addWorksheet('Skill Matrix');
  skillSheet.columns = [
    { header: 'Skill', key: 'topic' },
    { header: 'Level', key: 'level' },
    { header: 'Score', key: 'score' },
    { header: 'Problems Solved', key: 'solved' },
    { header: 'Platforms', key: 'platforms' },
  ];
  skillSheet.addRows(
    student.skills.map((s) => ({
      topic: s.topic,
      level: s.level,
      score: s.score,
      solved: s.problemsSolved,
      platforms: s.platformCount,
    })),
  );
  styleHeader(skillSheet);
  autoWidth(skillSheet);

  // -- Contests -------------------------------------------------------------
  const contestSheet = workbook.addWorksheet('Contests');
  contestSheet.columns = [
    { header: 'Platform', key: 'platform' },
    { header: 'Contest', key: 'name' },
    { header: 'Date', key: 'date' },
    { header: 'Rank', key: 'rank' },
    { header: 'Rating Before', key: 'before' },
    { header: 'Rating After', key: 'after' },
    { header: 'Change', key: 'change' },
    { header: 'Problems Solved', key: 'solved' },
  ];
  contestSheet.addRows(
    contests.data.map((c) => ({
      platform: PLATFORMS[c.platform].label,
      name: c.name,
      date: c.date ? c.date.toISOString().slice(0, 10) : 'N/A',
      rank: show(c.rank),
      before: show(c.ratingBefore),
      after: show(c.ratingAfter),
      change: show(c.ratingChange),
      solved: show(c.problemsSolved),
    })),
  );
  styleHeader(contestSheet);
  autoWidth(contestSheet);

  // -- Rating history -------------------------------------------------------
  const ratingSheet = workbook.addWorksheet('Rating History');
  ratingSheet.columns = [
    { header: 'Platform', key: 'platform' },
    { header: 'Date', key: 'date' },
    { header: 'Rating', key: 'rating' },
    { header: 'Contest', key: 'contest' },
  ];
  for (const series of ratings.series) {
    for (const point of series.points) {
      ratingSheet.addRow({
        platform: series.label,
        date: point.date.toISOString().slice(0, 10),
        rating: point.rating,
        contest: point.contestName ?? '',
      });
    }
  }
  styleHeader(ratingSheet);
  autoWidth(ratingSheet);

  // -- Growth over time -----------------------------------------------------
  const growth = workbook.addWorksheet('Growth');
  growth.columns = [
    { header: 'Date', key: 'date' },
    { header: 'Problems Solved', key: 'solved' },
    { header: 'Rating', key: 'rating' },
    { header: 'Contests', key: 'contests' },
    { header: 'CP Score', key: 'score' },
  ];
  growth.addRows(
    history.map((h) => ({
      date: h.date.toISOString().slice(0, 10),
      solved: show(h.totalSolved),
      rating: show(h.rating),
      contests: show(h.contestsAttended),
      score: show(h.cpScore),
    })),
  );
  styleHeader(growth);
  autoWidth(growth);

  return { buffer: await workbookToBuffer(workbook, format), filename, contentType: CONTENT_TYPES[format] };
}

// ---------------------------------------------------------------------------
// Batch report
// ---------------------------------------------------------------------------

export async function generateBatchReport(batch: string, format: ReportFormat): Promise<GeneratedReport> {
  const analytics = await getBatchAnalytics(batch);
  if (analytics.studentCount === 0) throw notFound(`No students found in batch "${batch}"`);

  const [leaderboard, topics] = await Promise.all([
    getLeaderboard({ batch }, { pageSize: 200 }),
    getTopicAnalytics({ batch }),
  ]);

  const filename = `batch-report-${safeName(batch)}.${format}`;

  if (format === 'pdf') {
    return { buffer: await renderBatchPdf(analytics, leaderboard.data), filename, contentType: CONTENT_TYPES.pdf };
  }

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Competitive Programming Student Performance Tracker';

  const leaderboardSheet = workbook.addWorksheet('Leaderboard');
  leaderboardSheet.columns = [
    { header: 'Rank', key: 'rank' },
    { header: 'Student ID', key: 'studentId' },
    { header: 'Name', key: 'name' },
    { header: 'College', key: 'college' },
    { header: 'Branch', key: 'branch' },
    { header: 'Problems Solved', key: 'solved' },
    { header: 'Easy', key: 'easy' },
    { header: 'Medium', key: 'medium' },
    { header: 'Hard', key: 'hard' },
    { header: 'Contest Rating', key: 'rating' },
    { header: 'Contests', key: 'contests' },
    { header: 'Topics', key: 'topics' },
    { header: 'CP Score', key: 'score' },
  ];
  leaderboardSheet.addRows(
    leaderboard.data.map((row) => ({
      rank: row.rank,
      studentId: row.studentId,
      name: row.name,
      college: row.college ?? 'N/A',
      branch: row.branch ?? 'N/A',
      solved: row.totalSolved,
      easy: row.difficultyKnown ? row.easySolved : 'N/A',
      medium: row.difficultyKnown ? row.mediumSolved : 'N/A',
      hard: row.difficultyKnown ? row.hardSolved : 'N/A',
      rating: show(row.currentRating),
      contests: row.contestsKnown ? row.totalContests : 'N/A',
      topics: row.topicCount,
      score: row.cpScore,
    })),
  );
  styleHeader(leaderboardSheet);
  autoWidth(leaderboardSheet);

  const statsSheet = workbook.addWorksheet('Batch Statistics');
  statsSheet.columns = [
    { header: 'Metric', key: 'metric' },
    { header: 'Average', key: 'average' },
    { header: 'Median', key: 'median' },
    { header: 'Min', key: 'min' },
    { header: 'Max', key: 'max' },
    { header: 'Students', key: 'count' },
  ];
  for (const [metric, dist] of Object.entries(analytics.averages)) {
    statsSheet.addRow({
      metric,
      average: show(dist.average),
      median: show(dist.median),
      min: show(dist.min),
      max: show(dist.max),
      count: dist.count,
    });
  }
  styleHeader(statsSheet);
  autoWidth(statsSheet);

  const platformSheet = workbook.addWorksheet('Platform Adoption');
  platformSheet.columns = [
    { header: 'Platform', key: 'platform' },
    { header: 'Profiles Linked', key: 'linked' },
    { header: 'Data Available', key: 'available' },
    { header: 'Adoption %', key: 'adoption' },
  ];
  platformSheet.addRows(
    analytics.platformAdoption.map((p) => ({
      platform: p.label,
      linked: p.linked,
      available: p.available,
      adoption: p.adoptionRate,
    })),
  );
  styleHeader(platformSheet);
  autoWidth(platformSheet);

  const topicSheet = workbook.addWorksheet('Topic Analysis');
  topicSheet.columns = [
    { header: 'Topic', key: 'topic' },
    { header: 'Problems Solved', key: 'solved' },
    { header: 'Students', key: 'students' },
    { header: 'Share %', key: 'share' },
  ];
  topicSheet.addRows(
    topics.topics.map((t) => ({ topic: t.topic, solved: t.problemsSolved, students: t.studentCount, share: t.share })),
  );
  styleHeader(topicSheet);
  autoWidth(topicSheet);

  return { buffer: await workbookToBuffer(workbook, format), filename, contentType: CONTENT_TYPES[format] };
}

// ---------------------------------------------------------------------------
// Leaderboard / student list export
// ---------------------------------------------------------------------------

export async function generateLeaderboardExport(
  filters: StudentFilters,
  format: 'xlsx' | 'csv',
  limit = 1000,
): Promise<GeneratedReport> {
  const leaderboard = await getLeaderboard(filters, { pageSize: Math.min(200, limit) });
  const pages = Math.min(Math.ceil(limit / 200), leaderboard.pagination.totalPages);

  const rows = [...leaderboard.data];
  for (let page = 2; page <= pages; page++) {
    const next = await getLeaderboard(filters, { pageSize: 200, page });
    rows.push(...next.data);
  }

  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Leaderboard');
  sheet.columns = [
    { header: 'Rank', key: 'rank' },
    { header: 'Student ID', key: 'studentId' },
    { header: 'Name', key: 'name' },
    { header: 'College', key: 'college' },
    { header: 'Batch', key: 'batch' },
    { header: 'Branch', key: 'branch' },
    { header: 'Problems Solved', key: 'solved' },
    { header: 'Contest Rating', key: 'rating' },
    { header: 'Contests', key: 'contests' },
    { header: 'Topic Coverage %', key: 'coverage' },
    { header: 'CP Score', key: 'score' },
  ];
  sheet.addRows(
    rows.slice(0, limit).map((row) => ({
      rank: row.rank,
      studentId: row.studentId,
      name: row.name,
      college: row.college ?? 'N/A',
      batch: row.batch ?? 'N/A',
      branch: row.branch ?? 'N/A',
      solved: row.totalSolved,
      rating: show(row.currentRating),
      contests: row.contestsKnown ? row.totalContests : 'N/A',
      coverage: row.topicsKnown ? row.topicCoverage : 'N/A',
      score: row.cpScore,
    })),
  );
  styleHeader(sheet);
  autoWidth(sheet);

  return {
    buffer: await workbookToBuffer(workbook, format),
    filename: `leaderboard.${format}`,
    contentType: CONTENT_TYPES[format],
  };
}

/** Failed-profile export for the error dashboard. */
export async function generateFailureReport(format: 'xlsx' | 'csv', jobId?: string): Promise<GeneratedReport> {
  const items = await prisma.processingJobItem.findMany({
    where: { status: { in: ['FAILED', 'RATE_LIMITED'] }, ...(jobId ? { jobId } : {}) },
    include: { student: { select: { studentId: true, name: true } }, job: { select: { number: true } } },
    orderBy: { updatedAt: 'desc' },
    take: 10_000,
  });

  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Failures');
  sheet.columns = [
    { header: 'Job', key: 'job' },
    { header: 'Student ID', key: 'studentId' },
    { header: 'Student', key: 'name' },
    { header: 'Platform', key: 'platform' },
    { header: 'Status', key: 'status' },
    { header: 'Data Status', key: 'dataStatus' },
    { header: 'Attempts', key: 'attempts' },
    { header: 'Error', key: 'error' },
    { header: 'Last Attempt', key: 'lastAttempt' },
  ];
  sheet.addRows(
    items.map((item) => ({
      job: `#${item.job.number}`,
      studentId: item.student.studentId,
      name: item.student.name,
      platform: PLATFORMS[item.platform].label,
      status: item.status,
      dataStatus: item.dataStatus ?? 'N/A',
      attempts: item.attempts,
      error: item.lastError ?? '',
      lastAttempt: item.finishedAt?.toISOString() ?? '',
    })),
  );
  styleHeader(sheet);
  autoWidth(sheet);

  return {
    buffer: await workbookToBuffer(workbook, format),
    filename: `failed-profiles.${format}`,
    contentType: CONTENT_TYPES[format],
  };
}

// ---------------------------------------------------------------------------
// PDF rendering
// ---------------------------------------------------------------------------

const INK = '#0F172A';
const MUTED = '#64748B';
const RULE = '#E2E8F0';

function pdfToBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

function pdfHeading(doc: PDFKit.PDFDocument, text: string) {
  if (doc.y > doc.page.height - 140) doc.addPage();
  doc.moveDown(0.8);
  doc.fillColor(INK).fontSize(13).font('Helvetica-Bold').text(text);
  doc.moveTo(doc.x, doc.y + 3).lineTo(doc.page.width - doc.page.margins.right, doc.y + 3).strokeColor(RULE).stroke();
  doc.moveDown(0.6);
}

function pdfTable(doc: PDFKit.PDFDocument, headers: string[], rows: (string | number)[][], widths: number[]) {
  const left = doc.page.margins.left;
  const drawRow = (cells: (string | number)[], bold: boolean) => {
    if (doc.y > doc.page.height - 70) {
      doc.addPage();
    }
    const y = doc.y;
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9).fillColor(bold ? INK : '#334155');
    let x = left;
    cells.forEach((cell, i) => {
      doc.text(String(cell), x, y, { width: widths[i]! - 6, ellipsis: true, lineBreak: false });
      x += widths[i]!;
    });
    doc.y = y + 15;
  };

  drawRow(headers, true);
  doc.moveTo(left, doc.y - 3).lineTo(left + widths.reduce((a, b) => a + b, 0), doc.y - 3).strokeColor(RULE).stroke();
  for (const row of rows) drawRow(row, false);
}

/** Horizontal bar chart drawn with primitives — no chart library needed. */
function pdfBars(doc: PDFKit.PDFDocument, entries: { label: string; value: number; color?: string }[], maxWidth = 260) {
  const max = Math.max(1, ...entries.map((e) => e.value));
  const left = doc.page.margins.left;
  for (const entry of entries) {
    if (doc.y > doc.page.height - 70) doc.addPage();
    const y = doc.y;
    doc.font('Helvetica').fontSize(9).fillColor('#334155').text(entry.label, left, y, { width: 130, ellipsis: true, lineBreak: false });
    const width = Math.max(2, (entry.value / max) * maxWidth);
    doc.rect(left + 140, y - 1, width, 9).fill(entry.color ?? '#2563EB');
    doc.fillColor('#334155').font('Helvetica').fontSize(9).text(String(entry.value), left + 145 + maxWidth, y, { lineBreak: false });
    doc.y = y + 15;
  }
}

async function renderStudentPdf(
  student: Awaited<ReturnType<typeof getStudentDetail>>,
  topics: Awaited<ReturnType<typeof getStudentTopics>>,
  contests: Awaited<ReturnType<typeof getStudentContests>>,
  history: Awaited<ReturnType<typeof getStudentHistory>>,
): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 42, info: { Title: `Student Report — ${student.name}` } });
  const a = student.analytics;

  doc.fillColor(INK).fontSize(20).font('Helvetica-Bold').text(student.name);
  doc
    .fillColor(MUTED)
    .fontSize(10)
    .font('Helvetica')
    .text(
      [`Student ID: ${student.studentId}`, student.branch, student.batch, student.college].filter(Boolean).join('  |  '),
    );
  doc.moveDown(0.3);
  doc.fillColor(MUTED).fontSize(8).text(`Generated ${new Date().toUTCString()}`);

  pdfHeading(doc, 'Competitive Programming Score');
  if (a?.hasData) {
    doc.fillColor(INK).fontSize(28).font('Helvetica-Bold').text(`${a.cpScore} / 100`);
    doc.fillColor(MUTED).fontSize(8).font('Helvetica').text('Generated by this application from public platform data. Not an official platform metric.');
  } else {
    doc.fillColor(MUTED).fontSize(11).font('Helvetica').text('N/A — no platform data has been retrieved for this student yet.');
  }

  pdfHeading(doc, 'Platform Profiles');
  pdfTable(
    doc,
    ['Platform', 'Username', 'Status', 'Solved', 'Rating', 'Contests'],
    student.platforms.map((p) => [
      PLATFORMS[p.platform].label,
      p.username,
      p.status,
      show(p.totalSolved),
      show(p.rating),
      show(p.contestsAttended),
    ]),
    [90, 120, 90, 60, 60, 60],
  );

  pdfHeading(doc, 'Problems by Platform');
  const platformBars = student.platforms
    .filter((p) => p.totalSolved !== null)
    .map((p) => ({ label: PLATFORMS[p.platform].label, value: p.totalSolved!, color: PLATFORMS[p.platform].colors.light }));
  if (platformBars.length > 0) pdfBars(doc, platformBars);
  else doc.fillColor(MUTED).fontSize(10).text('No platform published a solved count for this student.');

  if (a?.difficultyKnown) {
    pdfHeading(doc, 'Difficulty Distribution');
    pdfBars(doc, [
      { label: 'Easy', value: a.easySolved, color: '#16A34A' },
      { label: 'Medium', value: a.mediumSolved, color: '#D97706' },
      { label: 'Hard', value: a.hardSolved, color: '#DC2626' },
      {
        label: 'Unclassified',
        value: Math.max(0, a.totalSolved - a.easySolved - a.mediumSolved - a.hardSolved),
        color: '#94A3B8',
      },
    ]);
  } else if (a?.hasData) {
    pdfHeading(doc, 'Difficulty Distribution');
    doc
      .fillColor(MUTED)
      .fontSize(10)
      .font('Helvetica')
      .text('N/A — none of the platforms with data for this student publish an Easy/Medium/Hard split.');
  }

  pdfHeading(doc, 'Top Topics');
  if (topics.unified.length > 0) {
    pdfBars(doc, topics.unified.slice(0, 12).map((t) => ({ label: t.topic, value: t.problemsSolved })));
  } else {
    doc.fillColor(MUTED).fontSize(10).text('No topic breakdown is publicly available for this student.');
  }

  pdfHeading(doc, 'Skill Matrix');
  if (student.skills.length > 0) {
    pdfTable(
      doc,
      ['Skill', 'Level', 'Problems', 'Platforms'],
      student.skills.slice(0, 18).map((s) => [s.topic, s.level, s.problemsSolved, s.platformCount]),
      [190, 110, 80, 80],
    );
  } else {
    doc.fillColor(MUTED).fontSize(10).text('Not enough topic data to build a skill matrix.');
  }

  pdfHeading(doc, 'Contest Performance');
  doc
    .fillColor('#334155')
    .fontSize(10)
    .font('Helvetica')
    .text(
      `Contests: ${contests.summary.total}   |   Best rank: ${show(contests.summary.bestRank)}   |   Average rank: ${show(contests.summary.averageRank)}`,
    );
  doc.moveDown(0.4);
  if (contests.data.length > 0) {
    pdfTable(
      doc,
      ['Platform', 'Contest', 'Date', 'Rank', 'Change'],
      contests.data.slice(0, 20).map((c) => [
        PLATFORMS[c.platform].label,
        c.name,
        c.date ? c.date.toISOString().slice(0, 10) : 'N/A',
        show(c.rank),
        show(c.ratingChange),
      ]),
      [80, 190, 80, 60, 60],
    );
  } else {
    doc.fillColor(MUTED).fontSize(10).text('No contest history is publicly available for this student.');
  }

  if (history.length > 1) {
    pdfHeading(doc, 'Growth Over Time');
    pdfTable(
      doc,
      ['Date', 'Solved', 'Rating', 'Contests', 'CP Score'],
      history.slice(-15).map((h) => [
        h.date.toISOString().slice(0, 10),
        show(h.totalSolved),
        show(h.rating),
        show(h.contestsAttended),
        show(h.cpScore),
      ]),
      [110, 90, 90, 90, 90],
    );
  }

  return pdfToBuffer(doc);
}

async function renderBatchPdf(
  analytics: Awaited<ReturnType<typeof getBatchAnalytics>>,
  leaderboard: Awaited<ReturnType<typeof getLeaderboard>>['data'],
): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 42, info: { Title: `Batch Report — ${analytics.batch}` } });

  doc.fillColor(INK).fontSize(20).font('Helvetica-Bold').text(`Batch ${analytics.batch}`);
  doc
    .fillColor(MUTED)
    .fontSize(10)
    .font('Helvetica')
    .text(`${analytics.studentCount} students  |  ${analytics.studentsWithData} with retrieved data`);
  doc.fillColor(MUTED).fontSize(8).text(`Generated ${new Date().toUTCString()}`);

  pdfHeading(doc, 'Batch Statistics');
  pdfTable(
    doc,
    ['Metric', 'Average', 'Median', 'Min', 'Max'],
    Object.entries(analytics.averages).map(([metric, dist]) => [
      metric.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()),
      show(dist.average),
      show(dist.median),
      show(dist.min),
      show(dist.max),
    ]),
    [160, 90, 90, 80, 80],
  );

  pdfHeading(doc, 'Highlights');
  const h = analytics.highlights;
  pdfTable(
    doc,
    ['Category', 'Student', 'Value'],
    [
      ['Top CP Score', h.topStudent?.name ?? 'N/A', h.topStudent?.cpScore ?? 'N/A'],
      ['Most Problems Solved', h.mostProblemsSolved?.name ?? 'N/A', h.mostProblemsSolved?.totalSolved ?? 'N/A'],
      ['Highest Rating', h.highestRating?.name ?? 'N/A', h.highestRating?.bestRating ?? 'N/A'],
    ],
    [170, 200, 130],
  );

  pdfHeading(doc, 'Top 10 Students');
  pdfTable(
    doc,
    ['#', 'Student', 'Solved', 'Rating', 'Contests', 'Score'],
    leaderboard.slice(0, 10).map((row) => [
      row.rank,
      row.name,
      row.totalSolved,
      show(row.currentRating),
      row.totalContests,
      row.cpScore,
    ]),
    [30, 190, 70, 70, 70, 70],
  );

  pdfHeading(doc, 'Platform Adoption');
  pdfBars(
    doc,
    analytics.platformAdoption.map((p) => ({ label: p.label, value: p.linked, color: p.color })),
  );

  pdfHeading(doc, 'Strongest Topics');
  pdfBars(doc, analytics.strengths.map((t) => ({ label: t.topic, value: t.problemsSolved })));

  pdfHeading(doc, 'Weakest Topics');
  pdfBars(
    doc,
    analytics.weaknesses.map((t) => ({ label: t.topic, value: t.problemsSolved, color: '#94A3B8' })),
  );

  return pdfToBuffer(doc);
}
